SELECT C.ID
    FROM ECOLI_DATA C
    JOIN ECOLI_DATA P
    ON C.PARENT_ID = P.ID
JOIN ECOLI_DATA GP 
ON P.PARENT_ID = GP.ID
LEFT JOIN ECOLI_DATA GGP
ON GP.PARENT_ID = GGP.ID
WHERE GGP.ID IS NULL 
ORDER BY C.ID;
