WITH RECURSIVE GEN AS (
    -- 1세대
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 다음 세대
    SELECT C.ID, C.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA C
    JOIN GEN G
    ON C.PARENT_ID = G.ID
)
SELECT 
    COUNT(*) AS COUNT,
    G.GENERATION
FROM GEN G 
LEFT JOIN ECOLI_DATA C
ON G.ID = C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION;