SELECT i.ITEM_ID, i.ITEM_NAME , i.RARITY 
FROM ITEM_TREE t 
JOIN ITEM_INFO r ON t.PARENT_ITEM_ID = r.ITEM_ID
JOIN ITEM_INFO i ON t.ITEM_ID  = i.ITEM_ID
WHERE r.RARITY = 'RARE' 
ORDER BY i.ITEM_ID DESC